name: cleanup
on:
    push:
      branches:
        - main  # Replace 'main' with your desired branch
 
jobs:
    cleanup:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Run cleanup
          run: chmod +x cleanup.sh && ./cleanup.sh
  
          