name: cleanup
on:
    push:
      branches:
        - main  # Replace 'main' with your desired branch
 
jobs:
    cleanup:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: add a file to be deleted
          run: touch file.txt
        - name: add a script to delete the file
          run: echo "rm file.txt" > cleanup.sh
        - name: Run cleanup
          run: chmod +x cleanup.sh && ./cleanup.sh
        - name: check if file exists
          run: ls
  
          