name: Push Event Workflow

on:
  push:
    branches:
      - main  # Replace 'main' with your desired branch

jobs:
  print_message:
    runs-on: ubuntu-latest  # You can change the runner environment if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Print a message
        run: echo "Push event detected! Workflow is running."

