name: Secrets Workflow

on:
  push:
    branches:
      - main

jobs:
  use_secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display secrets
        run: |
          echo "API Key: ${{ secrets.API_KEY }}"
          echo "Database Password: ${{ secrets.DATABASE_PASSWORD }}"
