name: Terraform Apply

on:
  push:
    branches:
      - main  # Change this to the appropriate branch name

jobs:
  terraform_apply:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.5
      - name: Terraform init
        run: terraform init

      - name: Terraform apply
        run: terraform apply -auto-approve

    #   - name: Cleanup
    #     run: rm -rf .terraform
