name: Go Tests

on:
  push:
    branches:
      - main  # Change to your desired branch
  schedule:
#every 5 minutes
  - cron: "*/5 * * * *"  # Change to your desired cron schedule

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run cleanup
        run: chmod +x cleanup.sh && ./cleanup.sh

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20  # Change to your desired Go version
        
      - name: Test with go
        run: go test go_log_test.go main.go

      - name: Build
        run: go build -o main_build main.go  
